    1- Coloque os dados dos dois anos em um unico data frame

In [7]:
import pandas as pd

df1 = pd.read_csv("gasolina_2000+.csv", index_col=0)
df2 = pd.read_csv("gasolina_2010+.csv",index_col=0) 

df3 = pd.concat([df1,df2],axis=0)
df3

C:\Users\Mickael\AppData\Local\Temp\ipykernel_28008\3072768120.py:4: DtypeWarning: Columns (12,14,15,16,17,18) have mixed types. Specify dtype option on import or set low_memory=False.
  df2 = pd.read_csv("gasolina_2010+.csv",index_col=0)

,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO
0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,127,R$/l,1.288,0.016,1.190,1.350,0.463,0.012,0.825,0.11,0.4201,0.9666,0.133
1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387,R$/l,1.162,0.114,0.890,1.449,0.399,0.098,0.763,0.088,0.5013,1.05,0.115
2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,192,R$/l,1.389,0.097,1.180,1.760,0.419,0.070,0.97,0.095,0.5614,1.161,0.098
3,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,162,R$/l,1.262,0.070,1.090,1.509,0.432,0.055,0.83,0.119,0.5991,1.22242,0.143
4,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,ETANOL HIDRATADO,103,R$/l,1.181,0.078,1.050,1.400,0.24,0.066,0.941,0.077,0.7441,1.0317,0.082
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
120818,2021-04-25,2021-05-01,NORTE,RORAIMA,OLEO DIESEL S10,12,R$/l,4.582,0.056,4.510,4.690,-99999.0,0.012,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0
120819,2021-04-25,2021-05-01,SUL,SANTA CATARINA,OLEO DIESEL S10,100,R$/l,4.141,0.187,3.838,4.739,-99999.0,0.045,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0
120820,2021-04-25,2021-05-01,SUDESTE,SAO PAULO,OLEO DIESEL S10,886,R$/l,4.246,0.216,3.769,5.199,-99999.0,0.051,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0
120821,2021-04-25,2021-05-01,NORDESTE,SERGIPE,OLEO DIESEL S10,33,R$/l,4.464,0.205,4.190,4.699,-99999.0,0.046,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0
120822,2021-04-25,2021-05-01,NORTE,TOCANTINS,OLEO DIESEL S10,18,R$/l,4.352,0.156,4.199,4.699,-99999.0,0.036,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0

    2--Investigue as colunas e os dados que saem dela

In [8]:
df3.info()

<class 'pandas.core.frame.DataFrame'>
Index: 120823 entries, 0 to 120822
Data columns (total 18 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   DATA INICIAL                   120823 non-null  object
 1   DATA FINAL                     120823 non-null  object
 2   REGIÃO                         120823 non-null  object
 3   ESTADO                         120823 non-null  object
 4   PRODUTO                        120823 non-null  object
 5   NÚMERO DE POSTOS PESQUISADOS   120823 non-null  int64
 6   UNIDADE DE MEDIDA              120823 non-null  object
 7   PREÇO MÉDIO REVENDA            120823 non-null  float64
 8   DESVIO PADRÃO REVENDA          120823 non-null  float64
 9   PREÇO MÍNIMO REVENDA           120823 non-null  float64
 10  PREÇO MÁXIMO REVENDA           120823 non-null  float64
 11  MARGEM MÉDIA REVENDA           120823 non-null  object
 12  COEF DE VARIAÇÃO REVENDA       120823 non-null  float64
 13  PREÇO MÉDIO DISTRIBUIÇÃO       120823 non-null  object
 14  DESVIO PADRÃO DISTRIBUIÇÃO     120823 non-null  object
 15  PREÇO MÍNIMO DISTRIBUIÇÃO      120823 non-null  object
 16  PREÇO MÁXIMO DISTRIBUIÇÃO      120823 non-null  object
 17  COEF DE VARIAÇÃO DISTRIBUIÇÃO  120823 non-null  object
dtypes: float64(5), int64(1), object(12)
memory usage: 17.5+ MB

In [9]:
df3.head()

,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO
0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,127,R$/l,1.288,0.016,1.19,1.350,0.463,0.012,0.825,0.11,0.4201,0.9666,0.133
1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387,R$/l,1.162,0.114,0.89,1.449,0.399,0.098,0.763,0.088,0.5013,1.05,0.115
2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,192,R$/l,1.389,0.097,1.18,1.760,0.419,0.070,0.97,0.095,0.5614,1.161,0.098
3,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,162,R$/l,1.262,0.070,1.09,1.509,0.432,0.055,0.83,0.119,0.5991,1.22242,0.143
4,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,ETANOL HIDRATADO,103,R$/l,1.181,0.078,1.05,1.400,0.24,0.066,0.941,0.077,0.7441,1.0317,0.082

    --3 Selecione a 3 entrada da coluna DATA INICIAL e verifique o seu tipo

In [10]:
df3["DATA INICIAL"] [2]

'2004-05-09'

In [11]:
type(df3["DATA INICIAL"] [2])

str

    4 esta em string os valores de data inicial e data final, converta para data

In [28]:
pd.to_datetime(df3["DATA INICIAL"])

0        2004-05-09
1        2004-05-09
2        2004-05-09
3        2004-05-09
4        2004-05-09
            ...
120818   2021-04-25
120819   2021-04-25
120820   2021-04-25
120821   2021-04-25
120822   2021-04-25
Name: DATA INICIAL, Length: 120823, dtype: datetime64[ns]

In [35]:
df3["DATA FINAL"] = pd.to_datetime(df3["DATA FINAL"])

    5 utilizando algum metodo verifique todos os tipos de produtos presente na base de dados

In [32]:
df3.value_counts(df3["PRODUTO"])

PRODUTO
GASOLINA COMUM        23570
GLP                   23561
ETANOL HIDRATADO      23440
ÓLEO DIESEL           21194
GNV                   14469
ÓLEO DIESEL S10        9113
OLEO DIESEL S10        2376
OLEO DIESEL            2351
GASOLINA ADITIVADA      749
Name: count, dtype: int64

    6 filtre o DataFrame para obter os dados da gasoina comum e coloque em outra variavel

In [37]:
DFGasolina = df3[df3["PRODUTO"] == "GASOLINA COMUM"]

DFGasolina ##23 K DE LINHAS A QUANTIDADE EXATA NA FILTRAGEM ACIMA DA QUANTIDADE DA GASOLINA

,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,ANO-MES
12064,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,GASOLINA COMUM,128,R$/l,2.029,0.007,1.990,2.070,0.318,0.003,1.711,0.02,1.651,1.7427,0.012,2004/05
12065,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,GASOLINA COMUM,395,R$/l,2.025,0.062,1.850,2.220,0.296,0.031,1.729,0.036,1.6643,1.915,0.021,2004/05
12066,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,GASOLINA COMUM,194,R$/l,2.358,0.066,2.000,2.540,0.472,0.028,1.886,0.068,1.75,2.0713,0.036,2004/05
12067,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,GASOLINA COMUM,166,R$/l,2.120,0.075,1.970,2.440,0.325,0.035,1.795,0.033,1.70701,1.9703,0.018,2004/05
12068,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,GASOLINA COMUM,106,R$/l,2.090,0.034,2.000,2.159,0.35,0.016,1.74,0.042,1.6789,1.918,0.024,2004/05
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
120721,2021-04-25,2021-05-01,NORTE,RORAIMA,GASOLINA COMUM,12,R$/l,5.364,0.065,5.310,5.530,-99999.0,0.012,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,2021/05
120722,2021-04-25,2021-05-01,SUL,SANTA CATARINA,GASOLINA COMUM,119,R$/l,5.051,0.251,4.640,5.599,-99999.0,0.050,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,2021/05
120723,2021-04-25,2021-05-01,SUDESTE,SAO PAULO,GASOLINA COMUM,1187,R$/l,5.265,0.218,4.279,6.099,-99999.0,0.041,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,2021/05
120724,2021-04-25,2021-05-01,NORDESTE,SERGIPE,GASOLINA COMUM,34,R$/l,5.586,0.088,5.410,5.699,-99999.0,0.016,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,2021/05
120725,2021-04-25,2021-05-01,NORTE,TOCANTINS,GASOLINA COMUM,20,R$/l,5.751,0.160,5.578,6.119,-99999.0,0.028,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,2021/05

    7 Qual o preço medio de revenda da gasolina comum em agosto de 2008

In [36]:
df3['ANO-MES'] = df3["DATA FINAL"].apply(lambda x: "{}".format(x.year)) + df3["DATA FINAL"].apply(lambda x: "/{:02d}".format(x.month))

In [41]:
DFGasolina[DFGasolina['ANO-MES']== '2008/08']

,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,ANO-MES
17949,2008-07-27,2008-08-02,CENTRO OESTE,DISTRITO FEDERAL,GASOLINA COMUM,86,R$/l,2.573,0.021,2.520,2.599,0.372,0.008,2.201,0.068,2.0938,2.371,0.031,2008/08
17950,2008-07-27,2008-08-02,CENTRO OESTE,GOIAS,GASOLINA COMUM,255,R$/l,2.429,0.151,2.210,2.799,0.223,0.062,2.206,0.045,2.117,2.3442,0.02,2008/08
17951,2008-07-27,2008-08-02,CENTRO OESTE,MATO GROSSO,GASOLINA COMUM,143,R$/l,2.626,0.214,2.360,3.070,0.32,0.081,2.306,0.076,2.1977,2.5,0.033,2008/08
17952,2008-07-27,2008-08-02,CENTRO OESTE,MATO GROSSO DO SUL,GASOLINA COMUM,139,R$/l,2.718,0.074,2.548,2.899,0.446,0.027,2.272,0.055,2.1681,2.47,0.024,2008/08
17953,2008-07-27,2008-08-02,NORDESTE,ALAGOAS,GASOLINA COMUM,104,R$/l,2.768,0.056,2.590,2.930,0.475,0.020,2.293,0.046,2.1694,2.372,0.02,2008/08
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18079,2008-08-24,2008-08-30,SUDESTE,RIO DE JANEIRO,GASOLINA COMUM,737,R$/l,2.546,0.120,2.290,2.899,0.28,0.047,2.266,0.059,2.1533,2.4808,0.026,2008/08
18080,2008-08-24,2008-08-30,SUDESTE,SAO PAULO,GASOLINA COMUM,2380,R$/l,2.402,0.093,2.099,2.700,0.312,0.039,2.09,0.043,1.95,2.24,0.021,2008/08
18081,2008-08-24,2008-08-30,SUL,PARANA,GASOLINA COMUM,570,R$/l,2.438,0.083,2.140,2.850,0.312,0.034,2.126,0.049,1.947,2.2448,0.023,2008/08
18082,2008-08-24,2008-08-30,SUL,RIO GRANDE DO SUL,GASOLINA COMUM,620,R$/l,2.595,0.087,2.390,2.860,0.384,0.034,2.211,0.049,2.068,2.3909,0.022,2008/08
18083,2008-08-24,2008-08-30,SUL,SANTA CATARINA,GASOLINA COMUM,389,R$/l,2.553,0.071,2.299,2.811,0.391,0.028,2.162,0.045,2.0537,2.3428,0.021,2008/08

In [44]:
DFGasolinaAgosto = DFGasolina[DFGasolina['ANO-MES']== '2008/08']

    8 Qual o preço medio de revenda no mes acima

In [45]:
DFGasolinaAgosto['PREÇO MÉDIO REVENDA'].mean()

np.float64(2.6012444444444442)

    9 preço medio em março de 2014 da gasolina em são paulo

In [46]:
DFGasolina[(DFGasolina['ANO-MES'] == '2014/03') & (DFGasolina['ESTADO'] == 'SAO PAULO')]['PREÇO MÉDIO REVENDA'].mean()

np.float64(2.8760000000000003)

    10 Quais estados a gasolina ultrapassou a barreira dos 5 reais e quando ocorreu

In [50]:
DFGasolina[DFGasolina['PREÇO MÉDIO REVENDA'] > 5 ][['ESTADO', 'ANO-MES', 'PREÇO MÉDIO REVENDA']].head(20) ##Filtrei a lista de gasolina pra o preço maior que 5 e depois passei uma seleção de colunas em uma lista, onde nessa lista eu disse quais colunas eu queria sleecionar

                ESTADO  ANO-MES  PREÇO MÉDIO REVENDA
98201             ACRE  2018/05                5.053
98347             ACRE  2018/06                5.035
98493             ACRE  2018/06                5.038
98511   RIO DE JANEIRO  2018/06                5.016
98646             ACRE  2018/06                5.031
98797             ACRE  2018/06                5.036
98948             ACRE  2018/06                5.039
99098             ACRE  2018/07                5.021
99247             ACRE  2018/07                5.042
99398             ACRE  2018/07                5.038
99549             ACRE  2018/07                5.033
99701             ACRE  2018/08                5.031
99852             ACRE  2018/08                5.015
100003            ACRE  2018/08                5.023
100153            ACRE  2018/08                5.036
100302            ACRE  2018/09                5.018
100453            ACRE  2018/09                5.074
100604            ACRE  2018/09                5.129
100756            ACRE  2018/09                5.153
100774  RIO DE JANEIRO  2018/09                5.036

    11 se eu quiser colocar em ordemCrescente

In [52]:
DFGasolina[DFGasolina['PREÇO MÉDIO REVENDA'] > 5 ][['ESTADO', 'ANO-MES', 'PREÇO MÉDIO REVENDA']].sort_values(by="PREÇO MÉDIO REVENDA")

                ESTADO  ANO-MES  PREÇO MÉDIO REVENDA
120351        MARANHAO  2021/04                5.001
105873  RIO DE JANEIRO  2019/05                5.004
111991  RIO DE JANEIRO  2020/02                5.007
106849            ACRE  2019/07                5.009
101971  RIO DE JANEIRO  2018/11                5.010
...                ...      ...                  ...
119985            ACRE  2021/04                6.220
120163            ACRE  2021/04                6.227
120699            ACRE  2021/05                6.258
119807            ACRE  2021/03                6.277
119629            ACRE  2021/03                6.688

[353 rows x 3 columns]

    12 qual a media de preços da região sul em 2012

In [60]:
df2012 = DFGasolina[DFGasolina["DATA FINAL"].apply(lambda x: x.year) == 2012] ##converte e filtra para achar todos os dados de 2012
df2012

,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,ANO-MES
22728,2012-01-01,2012-01-07,CENTRO OESTE,DISTRITO FEDERAL,GASOLINA COMUM,80,R$/l,2.834,0.005,2.830,2.850,0.285,0.002,2.549,0.008,2.536,2.559,0.003,2012/01
22729,2012-01-01,2012-01-07,CENTRO OESTE,GOIAS,GASOLINA COMUM,256,R$/l,2.853,0.089,2.550,3.080,0.347,0.031,2.506,0.081,2.391,2.726,0.032,2012/01
22730,2012-01-01,2012-01-07,CENTRO OESTE,MATO GROSSO,GASOLINA COMUM,137,R$/l,2.996,0.078,2.790,3.250,0.464,0.026,2.532,0.069,2.329,2.68,0.027,2012/01
22731,2012-01-01,2012-01-07,CENTRO OESTE,MATO GROSSO DO SUL,GASOLINA COMUM,131,R$/l,2.728,0.147,2.530,3.048,0.33,0.054,2.398,0.056,2.295,2.55,0.023,2012/01
22732,2012-01-01,2012-01-07,NORDESTE,ALAGOAS,GASOLINA COMUM,97,R$/l,2.778,0.065,2.690,2.960,0.439,0.023,2.339,0.033,2.262,2.4367,0.014,2012/01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24127,2012-12-23,2012-12-29,SUDESTE,RIO DE JANEIRO,GASOLINA COMUM,736,R$/l,2.877,0.115,2.549,3.799,0.357,0.040,2.52,0.058,2.335,2.7009,0.023,2012/12
24128,2012-12-23,2012-12-29,SUDESTE,SAO PAULO,GASOLINA COMUM,2376,R$/l,2.639,0.108,2.269,2.999,0.376,0.041,2.263,0.063,2.11,2.5222,0.028,2012/12
24129,2012-12-23,2012-12-29,SUL,PARANA,GASOLINA COMUM,564,R$/l,2.805,0.076,2.530,3.150,0.413,0.027,2.392,0.049,2.2336,2.595,0.02,2012/12
24130,2012-12-23,2012-12-29,SUL,RIO GRANDE DO SUL,GASOLINA COMUM,616,R$/l,2.775,0.099,2.530,3.099,0.415,0.036,2.36,0.048,2.244,2.5354,0.02,2012/12
24131,2012-12-23,2012-12-29,SUL,SANTA CATARINA,GASOLINA COMUM,386,R$/l,2.747,0.094,2.350,2.999,0.394,0.034,2.353,0.038,2.24,2.45,0.016,2012/12

In [61]:
df2012[df2012["REGIÃO"] == "SUL"]['PREÇO MÉDIO REVENDA'].mean()

np.float64(2.7214423076923073)

    13 VOcê conseguiria a variação percentual ano a ano do rj

In [68]:

DFGasolina['MES'] = DFGasolina["DATA FINAL"].apply(lambda x: x.month)

DFRio = DFGasolina[DFGasolina['ESTADO'] == 'RIO DE JANEIRO' ]

C:\Users\Mickael\AppData\Local\Temp\ipykernel_28008\1459795274.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DFGasolina['MES'] = DFGasolina["DATA FINAL"].apply(lambda x: x.month)

In [73]:
DFMES_RIO = DFRio.groupby('ANO-MES')[['PREÇO MÉDIO REVENDA',"MES"]].last()

#Aqui vai ser complicado para criar a variação, admito que não consegui e tive que ver a aul, mas tem duas funções extras que ajudam,
#O shift() que serve para descolocar os valores na unidade e então voce faz o calculo para porcentagem, VEJA:

(DFMES_RIO[DFMES_RIO["MES"]==12]/DFMES_RIO[DFMES_RIO["MES"]==12].shift(1) - 1) *100 #calculo da variação percentual

         PREÇO MÉDIO REVENDA  MES
ANO-MES
2004/12                  NaN  NaN
2005/12             9.233449  0.0
2006/12             0.917065  0.0
2007/12             0.355591  0.0
2008/12             0.984252  0.0
2009/12             1.637427  0.0
2010/12             2.032988  0.0
2011/12             7.105263  0.0
2012/12             0.982801  0.0
2013/12             6.777894  0.0
2014/12             4.361979  0.0
2015/12            20.461634  0.0
2016/12             3.625065  0.0
2017/12            13.643178  0.0
2018/12             5.804749  0.0
2019/12             3.802993  0.0
2020/12            -1.321321  0.0